apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-frontend-ws-cert
  namespace: chat-backend
spec:
  secretName: chat-frontend-ws-cert-secret
  issuerRef:
    name: cloudflare-cluster-issuer # Corrected name
    kind: ClusterIssuer
  commonName: api.succeedex.in
  dnsNames:
    # - chat.succeedex.in
    - api.succeedex.in
