# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy # Base64 encoded "mongouser"
  mongo-root-password: c2VjcmV0MTIz # Base64 encoded "secret123"
  mongo-db-name: Y2hhdA== # Base64 encoded "chat"
